bot:
  TOKEN: '6300921956:AAHwT-FhyiVXipdT_BIQHavPs-6rie5LpPw'
  ADMIN_CHAT_ID: 290569556
  LOCAL_API_URL: null
  ALLOWED_CHATS: []

download:
  DOWNLOAD_SEMAPHORE: 5
  DOWNLOAD_LIMIT_PER_HOUR: 3
  READ_TIMEOUT: 1800
  WRITE_TIMEOUT: 1800

logging:
  LOG_FILE: "telegram_youtube_bot_err.log"
  LOG_MAX_SIZE_MB: 1

features:
  TEST_MODE: false
  CACHE_ENABLED: true
